using System.Collections.Generic;

namespace TripFund.App.Constants
{
    public record IsoCurrencyInfo(string Code, string Symbol, int Decimals, string Name);

    public static class IsoCurrencies
    {
        public static readonly List<IsoCurrencyInfo> All = new()
        {
            new("EUR", "€", 2, "Euro"),
            new("USD", "$", 2, "United States Dollar"),
            new("GBP", "£", 2, "British Pound Sterling"),
            new("JPY", "¥", 0, "Japanese Yen"),
            new("CHF", "CHF", 2, "Swiss Franc"),
            new("CAD", "$", 2, "Canadian Dollar"),
            new("AUD", "$", 2, "Australian Dollar"),
            new("CNY", "¥", 2, "Chinese Yuan"),
            new("SEK", "kr", 2, "Swedish Krona"),
            new("NZD", "$", 2, "New Zealand Dollar"),
            new("KRW", "₩", 0, "South Korean Won"),
            new("SGD", "$", 2, "Singapore Dollar"),
            new("NOK", "kr", 2, "Norwegian Krone"),
            new("MXN", "$", 2, "Mexican Peso"),
            new("INR", "₹", 2, "Indian Rupee"),
            new("RUB", "₽", 2, "Russian Ruble"),
            new("ZAR", "R", 2, "South African Rand"),
            new("TRY", "₺", 2, "Turkish Lira"),
            new("BRL", "R$", 2, "Brazilian Real"),
            new("TWD", "NT$", 2, "New Taiwan Dollar"),
            new("DKK", "kr", 2, "Danish Krone"),
            new("PLN", "zł", 2, "Polish Zloty"),
            new("THB", "฿", 2, "Thai Baht"),
            new("IDR", "Rp", 2, "Indonesian Rupiah"),
            new("HUF", "Ft", 2, "Hungarian Forint"),
            new("CZK", "Kč", 2, "Czech Koruna"),
            new("ILS", "₪", 2, "Israeli New Shekel"),
            new("CLP", "$", 0, "Chilean Peso"),
            new("PHP", "₱", 2, "Philippine Peso"),
            new("AED", "د.إ", 2, "United Arab Emirates Dirham"),
            new("COP", "$", 2, "Colombian Peso"),
            new("SAR", "﷼", 2, "Saudi Riyal"),
            new("MYR", "RM", 2, "Malaysian Ringgit"),
            new("RON", "lei", 2, "Romanian Leu"),
            new("ARS", "$", 2, "Argentine Peso"),
            new("PEN", "S/", 2, "Peruvian Sol"),
            new("UAH", "₴", 2, "Ukrainian Hryvnia"),
            new("VND", "₫", 0, "Vietnamese Dong"),
            new("EGP", "E£", 2, "Egyptian Pound"),
            new("BGN", "лв", 2, "Bulgarian Lev"),
            new("HRK", "kn", 2, "Croatian Kuna"),
            new("ISK", "kr", 0, "Icelandic Krona"),
            new("DOP", "RD$", 2, "Dominican Peso"),
            new("CRC", "₡", 2, "Costa Rican Colon"),
            new("UYU", "$U", 2, "Uruguayan Peso"),
            new("PYG", "Gs", 0, "Paraguayan Guarani"),
            new("BOB", "Bs.", 2, "Bolivian Boliviano"),
            new("GTQ", "Q", 2, "Guatemalan Quetzal"),
            new("HNL", "L", 2, "Honduran Lempira"),
            new("NIO", "C$", 2, "Nicaraguan Cordoba"),
            new("PAB", "B/.", 2, "Panamanian Balboa"),
            new("BHD", "BD", 3, "Bahraini Dinar"),
            new("JOD", "JD", 3, "Jordanian Dinar"),
            new("KWD", "KD", 3, "Kuwaiti Dinar"),
            new("OMR", "RO", 3, "Omani Rial"),
            new("QAR", "QR", 2, "Qatari Riyal"),
            new("LBP", "L£", 2, "Lebanese Pound"),
            new("MAD", "DH", 2, "Moroccan Dirham"),
            new("TND", "DT", 3, "Tunisian Dinar"),
            new("DZD", "DA", 2, "Algerian Dinar"),
            new("KZT", "₸", 2, "Kazakhstani Tenge"),
            new("UZS", "so'm", 2, "Uzbekistani Som"),
            new("GEL", "₾", 2, "Georgian Lari"),
            new("AMD", "֏", 2, "Armenian Dram"),
            new("AZN", "₼", 2, "Azerbaijani Manat"),
            new("XOF", "CFA", 0, "West African CFA Franc"),
            new("XAF", "FCFA", 0, "Central African CFA Franc"),
            new("XPF", "₣", 0, "CFP Franc"),
            new("LKR", "Rs", 2, "Sri Lankan Rupee"),
            new("PKR", "Rs", 2, "Pakistani Rupee"),
            new("BDT", "৳", 2, "Bangladeshi Taka"),
            new("NPR", "Rs", 2, "Nepalese Rupee"),
            new("MUR", "Rs", 2, "Mauritian Rupee"),
            new("SCR", "Rs", 2, "Seychellois Rupee"),
            new("KES", "Ksh", 2, "Kenyan Shilling"),
            new("TZS", "TSh", 2, "Tanzanian Shilling"),
            new("UGX", "USh", 0, "Ugandan Shilling"),
            new("NGN", "₦", 2, "Nigerian Naira"),
            new("GHS", "GH₵", 2, "Ghanaian Cedi"),
            new("ETB", "Br", 2, "Ethiopian Birr"),
            new("ZMW", "ZK", 2, "Zambian Kwacha"),
            new("BWP", "P", 2, "Botswana Pula"),
            new("NAD", "$", 2, "Namibian Dollar"),
            new("MZN", "MT", 2, "Mozambican Metical"),
            new("RWF", "RF", 0, "Rwandan Franc"),
            new("MGA", "Ar", 2, "Malagasy Ariary"),
            new("LSL", "L", 2, "Lesotho Loti"),
            new("SZL", "L", 2, "Swazi Lilangeni"),
            new("MKD", "ден", 2, "Macedonian Denar"),
            new("ALL", "Lek", 2, "Albanian Lek"),
            new("RSD", "дин.", 2, "Serbian Dinar"),
            new("BAM", "KM", 2, "Bosnia and Herzegovina Convertible Mark"),
            new("MDR", "L", 2, "Moldovan Leu"),
        };
    }
}
