using System.Collections.Generic;

namespace TripFund.App.Constants
{
    public record IsoCurrencyInfo(string Code, string Symbol, int Decimals, string Name);

    public static class IsoCurrencies
    {
        public static readonly List<IsoCurrencyInfo> All = new()
        {
            new("EUR", "€", 2, "Euro"),
            new("USD", "$", 2, "Dollaro Statunitense"),
            new("GBP", "£", 2, "Sterlina Britannica"),
            new("JPY", "¥", 0, "Yen Giapponese"),
            new("CHF", "CHF", 2, "Franco Svizzero"),
            new("CAD", "$", 2, "Dollaro Canadese"),
            new("AUD", "$", 2, "Dollaro Australiano"),
            new("CNY", "¥", 2, "Yuan Cinese"),
            new("SEK", "kr", 2, "Corona Svedese"),
            new("NZD", "$", 2, "Dollaro Neozelandese"),
            new("KRW", "₩", 0, "Won Sudcoreano"),
            new("SGD", "$", 2, "Dollaro di Singapore"),
            new("NOK", "kr", 2, "Corona Norvegese"),
            new("MXN", "$", 2, "Peso Messicano"),
            new("INR", "₹", 2, "Rupia Indiana"),
            new("RUB", "₽", 2, "Rublo Russo"),
            new("ZAR", "R", 2, "Rand Sudafricano"),
            new("TRY", "₺", 2, "Lira Turca"),
            new("BRL", "R$", 2, "Real Brasiliano"),
            new("TWD", "NT$", 2, "Nuovo Dollaro Taiwanese"),
            new("DKK", "kr", 2, "Corona Danese"),
            new("PLN", "zł", 2, "Zloty Polacco"),
            new("THB", "฿", 2, "Baht Thailandese"),
            new("IDR", "Rp", 2, "Rupia Indonesiana"),
            new("HUF", "Ft", 2, "Fiorino Ungherese"),
            new("CZK", "Kč", 2, "Corona Ceca"),
            new("ILS", "₪", 2, "Nuovo Shekel Israeliano"),
            new("CLP", "$", 0, "Peso Cileno"),
            new("PHP", "₱", 2, "Peso Filippino"),
            new("AED", "د.إ", 2, "Dirham degli Emirati Arabi Uniti"),
            new("COP", "$", 2, "Peso Colombiano"),
            new("SAR", "﷼", 2, "Riyal Saudita"),
            new("MYR", "RM", 2, "Ringgit Malese"),
            new("RON", "lei", 2, "Leu Rumeno"),
            new("ARS", "$", 2, "Peso Argentino"),
            new("PEN", "S/", 2, "Sol Peruviano"),
            new("UAH", "₴", 2, "Grivnia Ucraina"),
            new("VND", "₫", 0, "Dong Vietnamita"),
            new("EGP", "E£", 2, "Sterlina Egiziana"),
            new("BGN", "лв", 2, "Lev Bulgaro"),
            new("HRK", "kn", 2, "Kuna Croata"),
            new("ISK", "kr", 0, "Corona Islandese"),
            new("DOP", "RD$", 2, "Peso Dominicano"),
            new("CRC", "₡", 2, "Colón Costaricano"),
            new("UYU", "$U", 2, "Peso Uruguaiano"),
            new("PYG", "Gs", 0, "Guaraní Paraguaiano"),
            new("BOB", "Bs.", 2, "Boliviano"),
            new("GTQ", "Q", 2, "Quetzal Guatemalteco"),
            new("HNL", "L", 2, "Lempira Hoduregna"),
            new("NIO", "C$", 2, "Córdoba Nicaraguense"),
            new("PAB", "B/.", 2, "Balboa Panamanense"),
            new("BHD", "BD", 3, "Dinar del Bahrain"),
            new("JOD", "JD", 3, "Dinaro Giordano"),
            new("KWD", "KD", 3, "Dinaro Kuwaitiano"),
            new("OMR", "RO", 3, "Riyal Omanita"),
            new("QAR", "QR", 2, "Riyal del Qatar"),
            new("LBP", "L£", 2, "Sterlina Libanese"),
            new("MAD", "DH", 2, "Dirham Marocchino"),
            new("TND", "DT", 3, "Dinaro Tunisino"),
            new("DZD", "DA", 2, "Dinaro Algerino"),
            new("KZT", "₸", 2, "Tenge Kazako"),
            new("UZS", "so'm", 2, "Som Uzbeco"),
            new("GEL", "₾", 2, "Lari Georgiano"),
            new("AMD", "֏", 2, "Dram Armeno"),
            new("AZN", "₼", 2, "Manat Azero"),
            new("XOF", "CFA", 0, "Franco CFA BCEAO"),
            new("XAF", "FCFA", 0, "Franco CFA BEAC"),
            new("XPF", "₣", 0, "Franco CFP"),
            new("LKR", "Rs", 2, "Rupia di Sri Lanka"),
            new("PKR", "Rs", 2, "Rupia Pakistana"),
            new("BDT", "৳", 2, "Taka Bangladesh"),
            new("NPR", "Rs", 2, "Rupia Nepalese"),
            new("MUR", "Rs", 2, "Rupia Mauriziana"),
            new("SCR", "Rs", 2, "Rupia delle Seychelles"),
            new("KES", "Ksh", 2, "Scellino Keniota"),
            new("TZS", "TSh", 2, "Scellino Tanzaniano"),
            new("UGX", "USh", 0, "Scellino Ugandese"),
            new("NGN", "₦", 2, "Naira Nigeriana"),
            new("GHS", "GH₵", 2, "Cedi Ghanese"),
            new("ETB", "Br", 2, "Birr Etiopico"),
            new("ZMW", "ZK", 2, "Kwacha Zambiano"),
            new("BWP", "P", 2, "Pula del Botswana"),
            new("NAD", "$", 2, "Dollaro Namibiano"),
            new("MZN", "MT", 2, "Metical Mozambicano"),
            new("RWF", "RF", 0, "Franco Ruandese"),
            new("MGA", "Ar", 2, "Ariary Malgascio"),
            new("LSL", "L", 2, "Loti del Lesotho"),
            new("SZL", "L", 2, "Lilangeni dello Swaziland"),
            new("MKD", "den", 2, "Denar Macedone"),
            new("ALL", "Lek", 2, "Lek Albanese"),
            new("RSD", "дин.", 2, "Dinaro Serbo"),
            new("BAM", "KM", 2, "Marco Convertibile"),
            new("MDR", "L", 2, "Leu Moldavo"),
        };
    }
}
